on:
 workflow_dispatch:

jobs:
 job_1:
   strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest , windows-latest , macos-latest]
        node_version: [18.x,19.x,20.x]
   runs-on: ${{matrix.os}}
   steps:
    - uses: actions/setup-nodejs@v7.0.0
      with:
        node_version: ${{matrix.node_version}}
