on :
 workflow_dispatch:
   inputs:
     envirnoment:
       description: "Choose envirnoment"
       required: true
       default: "staging"
       type: choice
       options:
         - staging
         - production
jobs:
  deploy:
     runs-on: ubuntu-latest
     steps:
       - name : Deploy applocation
         run: echo "Deployment the application ....."
